### ISSUE TITLE
Trouble with bin ranges

### ISSUE THREAD

**Issue by maxsed** [dbuscombe-usgs/pyDGS#10]
Hi!
When using the Basic_usage notebook (single image), the ‘grain size bins’ (or ‘scales’ or ‘dat.getscales()’ I guess?) are mostly below 1 pixel, causing the data density in the domain of interest to be very low. How can I fix that the bins start from 1 pixel (assuming that I keep the resolution on 1), or increase the number of bins in a grainsize range of interest?
See attached PDF.

Cheers,
Max
[pyGDS_problems.pdf](https://github.com/dbuscombe-usgs/pyDGS/files/4769892/pyGDS_problems.pdf)

**Comment by ddbuscombe** [comment]
My apologies. This code has been modified for individual users' needs over the years and I have let it fall into a state of neglect. Please give me a few days to fix, test, and post a new version. Thanks

**Comment by ddbuscombe** [comment]
My apologies for the delay. A new version is posted that should fix your issues. See https://github.com/dbuscombe-usgs/pyDGS/issues/11#issuecomment-656829703
