### ISSUE TITLE
Units?

### ISSUE THREAD

**Issue by SiccarPoint** [dbuscombe-usgs/pyDGS#13]
Hi David. PyDGS is awesome! But I have a student getting really into the weeds of a bunch of unit conversions, and we are collectively starting to doubt ourselves. Would it be possible to make it clearer in the readme what the reported units actually are for the outputs? We have been assuming this is in pixels (or length, if a `resolution` is provided). But have then done a bang-up job of confusing ourselves over how this is fits with the `x` rescaling. We were expecting much larger values of `x` (2?) to go from a length to a volume, rather than the interval you specify?

**Comment by ddbuscombe** [comment]
It's Dan. Thanks!

I'm confused by your message but I suspect you are over thinking things. Units are pixels, unless you apply a scaling (resolution). `x` doesn't factor into the scaling. It modifies the distribution densities only - shifts the gsd left if x<0, and right if x>0. `x` comes from theory, but in relaity it is just usually used to fit 2d images to 3d measures of size like sieves. I hope that hlps!

**Comment by SiccarPoint** [comment]
Sorry for the garbling! That sounds reassuring! So am I right in thinking that the PDF as it comes with the default `x` is directly equivalent to a Wolman count? Or is there something more complex going on here?

**Comment by ddbuscombe** [comment]
in an Yes, that's right. A grid-by-number estimate. `x` is used to make the distribution more akin to what you would see in an area or volume by number. The theory is in Kellerhals' paper, then Diplas and colleagues tried to constrain its value. But my experience is that there are so many factors that I allow `x` to vary to fit reference measurements, such as on-screen manual grain diameter measurement. So, `x` is just a calibration parameter.

**Comment by SiccarPoint** [comment]
Thanks, that's really helpful. Will relay to Erin! She has a ton of high quality field data to calibrate to, but got herself really confused trying to work on it from first principles from Diplas...

**Comment by SiccarPoint** [comment]
> It's Dan. Thanks!

Oops! Sorry! I just absorbed this... My own name too!

**Comment by ddbuscombe** [comment]
No worries! Good luck! Let me know if you have more questions
