### ISSUE TITLE
Clarification Questions

### ISSUE THREAD

**Issue by KCrandall6** [dbuscombe-usgs/pyDGS#15]
Hi Daniel and pyDGS, 

I am a python beginner still learning, so bare with me here! I am trying to run pyDGS to analyze several high resolution photos of beach sands that I have. I have gotten the program to run, but am still a bit confused about a few things and was wondering if someone could help clarify them for me.

1. Am I correct in assuming that the program analyzes the entire picture? Therefore the picture should be cropped prior to being put through pyDGS? (I would need to crop out my scale in the picture)

2. Does the picture resolution/size matter? My photos are high resolution and I have tried cropping them down, so now they are about 2000x2000 pixels. Will this affect the test, and would I need to change anything prior to running the test other than the scaling?

3. Do I understand right that the maxscale variable determines up to what size the largest grains are in the image? i.e the smaller the maxscale value, the larger the grains are in the image? Or do I need to adjust this factor based on my image size? Also, does that mean there is no lower limit to grainsize other than what is outlined in the Buscombe (2013) paper? 

Any and all help or advice is welcomed!

Thanks,
Kurt

**Comment by ddbuscombe** [comment]
I'm very sorry for the delayed response.

1. You are correct that the program analyzes the entire picture. In fact it takes a subsample of rows from the images, analyzes the rows, and aggregates the observations for each row into a wavelet power spectrum, then computes grain size from that . You should mask/crop anything that isn't sediment, including scales, also mask out blur, vignette, etc
2. The high-resolution imagery works well
3. Maxscale is the number you divide the size of the image (say, 2000 px) to arrive at the largest considered grain size. So, if max_scale was 10, 2000/10 = 200 would be the largest grain size considered

I will be revisiting the code this week to see if I can make improvements to the code and docs to make these things more obvious (I admit they are not obvious, and I thank you for your patience)

**Comment by ddbuscombe** [comment]
Start with resolution=1. Look at those outputs. Adjust max_scale and 'x' parameters as necessary, then run again with the actual resolution, e.g. resolution=0.05 (or whatever)

**Comment by ddbuscombe** [comment]
I wrote a new utility to help you and others implement the pyDGS module. Go ahead and `git pull` (or download as zip), then use the program in [this way](https://github.com/dbuscombe-usgs/pyDGS#run_dgspy) 

You will be prompted to select files using a file browser. These are the images you wish to analyze. Make sure you play with the parameters (maxscale and x) to get a good result. Your resolution value should come from a calibration photo.

I'm going to close this issue now as resolved, but feel free to reopen if you are still having problems

**Comment by KCrandall6** [comment]
Hi Daniel, thank you for the update! I got the program to start but am running into an error that prevents me from getting any data outputs.

When I run the new run_dgs.py file, it goes for a little showing the progress bar moving to 100%, but after it completes nothing is saved to any excel files or images. When I run the program in VS Code, it tells me the following error after the progress bar completes to 100%:

~~~
FileNotFoundError: [Errno 2] No such file or directory: 'demo_results/stats_batch_2021-06-07-15-20.csv'
~~~

I decided to go back and try just the test.py file, not changing anything, and interestingly I also got an error which is the following:

~~~
cannot open data\IMG_0229.JPG
~~~

I've been playing around for a while trying to resolve this issue, but have not been able to fix it yet. I tried redownloading the zip file and also tried running the code both in VS Code and Anaconda's CMD.exe prompt but have not gotten past this error. I'm not sure if I am missing anything here? Any and all help is welcome!

**Comment by ddbuscombe** [comment]
It's telling you the directory `demo_results` doesnt exist, so check to see if it moved? Given that you cant run the test file either suggests you have moved files around or you're not following the instructions

**Comment by ddbuscombe** [comment]
I have tested all workflows on two windows computers and my instructions work as posted. Please follow the instructions, or get your adviser to help you troubleshoot. Closing issue - feel free to reopen if you feel like you have followed the instructions exactly, and have more specific errors - please dont email
