### ISSUE TITLE
typo in installation instructions, conda environment is pydgs2

### ISSUE THREAD

**Issue by iovereem** [dbuscombe-usgs/pyDGS#20]
Small typo.
In the readme instructions, you list the conda environment as pydgs, whereas it seems to be pydgs2?

So the switching to the environment would be:

> conda activate pydgs2

**Comment by ddbuscombe** [comment]
Oh good spot!! I will make that change - thanks

**Comment by ddbuscombe** [comment]
done - conda name is `pydgs`, the same as the instructions
