### ISSUE TITLE
TypeError: do_dgs() missing 1 required positional argument: 'filter'

### ISSUE THREAD

**Issue by iovereem** [dbuscombe-usgs/pyDGS#21]
Test code works for test images. 

Run_dgs code reports an error, if I use one of the images in isolation:

> python run_dgs.py -r 0.04 -m 10 -x 0.5 
for Cal_23.tif

Results in:
TypeError: do_dgs() missing 1 required positional argument: 'filter'

I tried giving it the filter = False argument (or True), did not change the message.

**Comment by ddbuscombe** [comment]
Thanks I'll take a look at it. The filter option is new, but I'm sure I just made a simple parsing error.... apologies! I'll post a revision

**Comment by ddbuscombe** [comment]
I switched from boolean to integer. Should now be fixed. And this time I tested properly ;) 

e.g.
`python run_dgs.py -r 0.04 -m 10 -x 0.5 -f 1`

f = 1 for filter
f = 0 for no filter

**Comment by iovereem** [comment]
Cool thanks, will try it!
 I am trying it against pebble bed photos for the Canning river in Alaska. 
(and then next on icebergs in fjords). I hope to make your webinar for CSDMS!

**Comment by ddbuscombe** [comment]
Awesome!!! I can't say I'm not jealous - looking forward to hearing how well pydgs works for you.

Going to close this issue now but feel free to reopen if the filter is not working
