### ISSUE TITLE
missing cwt package

### ISSUE THREAD

**Issue by peendebak** [dbuscombe-usgs/pyDGS#3]
When running the test code and installing with pip (Windows, anaconda) I get the following error:
```
ImportError: No module named 'cwt'
```
I could fix this by changing the code in `_dgs_class_web.py` from
```
import cwt
import sgolay
```
into
```
from . import cwt
from . import sgolay
```

**Comment by LaurenO654** [comment]
Hi @peendebak , thank you for posting this workaround! 
When you ran the initial DGS setup, did you use default settings for Cython 
`USE_CYTHON = TRUE`
or did you use alternative settings?
`USE_CYTHON = FALSE 
USE_CYTHON = 'auto'`

Thank you!
