### ISSUE TITLE
Error running test: ValueError: Buffer dtype mismatch, expected 'float64_t' but got 'float'

### ISSUE THREAD

**Issue by solomon-negusse** [dbuscombe-usgs/pyDGS#5]
Hello there, we are excited to try this tool and minimize physical sample collection but currently running into the following error running the test `python -c "import DGS; DGS.test.dotest_web()"` after installing with `python setup.py install`:

```
===========================================
======DIGITAL GRAIN SIZE: WAVELET==========
===========================================
=CALCULATE GRAIN SIZE-DISTRIBUTION FROM AN=
====IMAGE OF SEDIMENT/GRANULAR MATERIAL====
===========================================
======A PROGRAM BY DANIEL BUSCOMBE=========
=========NAU, FLAGSTAFF, ARIZONA===========
========REVISION 3.0.5, DEC 2017===========
===========================================
Input image is DGS/IMG_0229.JPG
Every 10 rows will be processed
Resolution is 1.0
Image will be filtered
Max scale as inverse fraction of data length: 8
Analysis of %s sub-octaves per octave: 8
Area to volume conversion constant = -0.5
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Processing image DGS/IMG_0229.JPG

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "DGS/test.py", line 52, in dotest_web
    DGS.dgs(image, density, resolution, dofilter, maxscale, notes, verbose, x)
  File "DGS/_dgs_class_web.py", line 250, in dgs
    useregion = filter_me(region) #, mn, nx, ny)
  File "DGS/_dgs_class_web.py", line 158, in filter_me
    Zf = sgolay.sgolay2d( region, window_size, order=3).getdata()
  File "DGS/sgolay.pyx", line 125, in DGS.sgolay.sgolay2d.__cinit__ (sgolay.c:3305)
    out = sp.fftconvolve(Z.astype('f'), m.astype('f'), mode='valid')
ValueError: Buffer dtype mismatch, expected 'float64_t' but got 'float'
```

- Environment:
  - OS: Ubuntu 16.04
  - Python 2.7.15

- Compiler:
  - GCC version 5.4.0 20160609

- Dependencies
  - Cython==0.28.2
  - numpy==1.14.3
  - Pillow==5.1.0
  - scipy==1.1.0

Any help in figuring out a solution to this issue would be appreciated!

**Comment by ddbuscombe** [comment]
Could you try recompiling the cython module DGS/sgolay.pyx and make a new static object

```
cython sgolay.pyx
gcc -c -fPIC -I/usr/include/python2.7/sgolay.c
gcc -shared sgolay.o -o sgolay.so
```

?

**Comment by solomon-negusse** [comment]
Thanks for the quick response Daniel! I tried those steps but still received the same error working in conda environment. But following your steps worked in pip|virtualenv environment. It's possible though that if I had tried with this set up initially, it may have worked without the manual compiling step. Thanks for making this tool open source!
