### ISSUE TITLE
ImportError: cannot import name 'cwt' from 'DGS'

### ISSUE THREAD

**Issue by sarcusa** [dbuscombe-usgs/pyDGS#6]
Hello Dan,
is there a fix for the following error: 

python -c "import DGS; DGS.test.dotest()"

Traceback (most recent call last):
  File "/home/user/Varves/pyDGS/DGS/_dgs_class_web.py", line 91, in <module>
    from DGS import cwt
ImportError: cannot import name 'cwt' from 'DGS' (/home/user/Varves/pyDGS/DGS/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/Varves/pyDGS/DGS/__init__.py", line 47, in <module>
    from DGS._dgs_class_web import dgs
  File "/home/user/Varves/pyDGS/DGS/_dgs_class_web.py", line 97, in <module>
    from . import cwt
ImportError: cannot import name 'cwt' from 'DGS' (/home/user/Varves/pyDGS/DGS/__init__.py)

I have tried installing pyDGS on my own Windows machine and again on a Linux machine and it says it is successful, I've also followed the "conda activate DGS" step but the error remains the same when I try the test or when I try the command "import DGS" in python.

Thanks very much, looking forward to using this tool for lake thin sections.

**Comment by ddbuscombe** [comment]
I believe this issue has [already been solved](https://github.com/dbuscombe-usgs/pyDGS/issues/3)?

**Comment by ddbuscombe** [comment]
Also, make sure you can see the grains in your thin sections in the photo (i.e. the grains are well resolved and non subpixel). Otherwise, this will be a non-starter

**Comment by sarcusa** [comment]
Yes, indeed I can see the changes are in the code _dgs_class_web.py but somehow it only works if I input the commands line by line. 

OK, we might need to rescan everything in that case. Thanks.
