### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Dramais** [dbuscombe-usgs/pyDGS#7]
Hello, 
I tried to install pyDGS but I have some troubles.

I'm working on windows10, with a x64 processor
I installed first phyton Python 3.7.3 and pip 19.1.1 and NumPy, then used the command
"pip install pyDGS" in windows cmd 

I get that
"C:\Users\guillaume.dramais>pip install pyDGS
Collecting pyDGS
  Using cached https://files.pythonhosted.org/packages/d9/63/dc20ec7afb04053c6133aa0120ed12d3dca9fe9bd1aeb023f30e8bd348b6/pyDGS-3.0.13.tar.gz
Requirement already satisfied: numpy in c:\users\guillaume.dramais\appdata\roaming\python\python37\site-packages (from pyDGS) (1.16.4)
Requirement already satisfied: scipy in c:\users\guillaume.dramais\appdata\roaming\python\python37\site-packages (from pyDGS) (1.3.0)
Requirement already satisfied: Pillow in c:\users\guillaume.dramais\appdata\local\programs\python\python37\lib\site-packages (from pyDGS) (6.0.0)
Requirement already satisfied: cython in c:\users\guillaume.dramais\appdata\local\programs\python\python37\lib\site-packages (from pyDGS) (0.29.10)
Building wheels for collected packages: pyDGS
  Building wheel for pyDGS (setup.py) ... error
  ERROR: Complete output from command 'c:\users\guillaume.dramais\appdata\local\programs\python\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\GUILLA~1.DRA\\AppData\\Local\\Temp\\pip-install-b7legdj7\\pyDGS\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\GUILLA~1.DRA\AppData\Local\Temp\pip-wheel-9y25j7cv' --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\DGS
  copying DGS\test.py -> build\lib.win-amd64-3.7\DGS
  copying DGS\_dgs_class_web.py -> build\lib.win-amd64-3.7\DGS
  copying DGS\__init__.py -> build\lib.win-amd64-3.7\DGS
  copying DGS\IMG_0202.JPG -> build\lib.win-amd64-3.7\DGS
  copying DGS\IMG_0229.JPG -> build\lib.win-amd64-3.7\DGS
  copying DGS\IMG_0249.JPG -> build\lib.win-amd64-3.7\DGS
  running build_ext
  building 'DGS.cwt' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for pyDGS
  Running setup.py clean for pyDGS
Failed to build pyDGS
Installing collected packages: pyDGS
  Running setup.py install for pyDGS ... error
    ERROR: Complete output from command 'c:\users\guillaume.dramais\appdata\local\programs\python\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\GUILLA~1.DRA\\AppData\\Local\\Temp\\pip-install-b7legdj7\\pyDGS\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GUILLA~1.DRA\AppData\Local\Temp\pip-record-r4uorotu\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\DGS
    copying DGS\test.py -> build\lib.win-amd64-3.7\DGS
    copying DGS\_dgs_class_web.py -> build\lib.win-amd64-3.7\DGS
    copying DGS\__init__.py -> build\lib.win-amd64-3.7\DGS
    copying DGS\IMG_0202.JPG -> build\lib.win-amd64-3.7\DGS
    copying DGS\IMG_0229.JPG -> build\lib.win-amd64-3.7\DGS
    copying DGS\IMG_0249.JPG -> build\lib.win-amd64-3.7\DGS
    running build_ext
    building 'DGS.cwt' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command "'c:\users\guillaume.dramais\appdata\local\programs\python\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\GUILLA~1.DRA\\AppData\\Local\\Temp\\pip-install-b7legdj7\\pyDGS\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GUILLA~1.DRA\AppData\Local\Temp\pip-record-r4uorotu\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\GUILLA~1.DRA\AppData\Local\Temp\pip-install-b7legdj7\pyDGS\

Then I tried with the latest anaconda version, with the prompt to send the commands 

"conda env create -f binder\environment.yml"
"conda activate DGS"

(base) C:\Users\guillaume.dramais>conda env create -f binder\environment.yml
WARNING: The conda.compat module is deprecated and will be removed in a future release.
WARNING: The conda.compat module is deprecated and will be removed in a future release.
EnvironmentFileNotFound: 'C:\Users\guillaume.dramais\binder\environment.yml' file not found
(base) C:\Users\guillaume.dramais>conda activate DGS
Could not find conda environment: DGS
You can list all discoverable environments with `conda info --envs`.
(base) C:\Users\guillaume.dramais>

But it's probably not the good way to install?
Thanks
Guillaume

**Comment by ddbuscombe** [comment]
For the pip installation, it tells you what the issue is: you don't have (or it can't see) a c++ compiler. 

```error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/```

For the conda installation, you need to be in the ```pyDGS``` directory in order for it to see the ```environment.tml``` file, so simply

```cd pyDGS```

*then* run ```conda env create -f binder\environment.yml```

**Comment by Dramais** [comment]
Hi Dan,
Thanks the installation works 

C:\Users\guillaume.dramais>pip install pyDGS
Requirement already satisfied: pyDGS in c:\users\guillaume.dramais\appdata\local\programs\python\python37\lib\site-packages (3.0.13)
Requirement already satisfied: scipy in c:\users\guillaume.dramais\appdata\roaming\python\python37\site-packages (from pyDGS) (1.3.0)
Requirement already satisfied: cython in c:\users\guillaume.dramais\appdata\local\programs\python\python37\lib\site-packages (from pyDGS) (0.29.10)
Requirement already satisfied: numpy in c:\users\guillaume.dramais\appdata\roaming\python\python37\site-packages (from pyDGS) (1.16.4)
Requirement already satisfied: Pillow in c:\users\guillaume.dramais\appdata\local\programs\python\python37\lib\site-packages (from pyDGS) (6.0.0)

The next step :

C:\Users\guillaume.dramais>python -c "import DGS; DGS.test.dotest()"
Traceback (most recent call last):
  File "C:\Users\guillaume.dramais\AppData\Local\Programs\Python\Python37\lib\site-packages\DGS\_dgs_class_web.py", line 101, in <module>
    from imread import imread
ModuleNotFoundError: No module named 'imread'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\guillaume.dramais\AppData\Local\Programs\Python\Python37\lib\site-packages\DGS\__init__.py", line 47, in <module>
    from DGS._dgs_class_web import dgs
  File "C:\Users\guillaume.dramais\AppData\Local\Programs\Python\Python37\lib\site-packages\DGS\_dgs_class_web.py", line 103, in <module>
    from scipy.misc import imread
ImportError: cannot import name 'imread' from 'scipy.misc' (C:\Users\guillaume.dramais\AppData\Roaming\Python\Python37\site-packages\scipy\misc\__init__.py)

Looks like a path problem? Or maybe not a problem. 
Where do I put the images to process

Thanks
Guillaume

**Comment by ddbuscombe** [comment]
```pip install Image```

or 

```pip install PIL```

**Comment by Dramais** [comment]
Thanks 

C:\Users\guillaume.dramais>pip install Image
Collecting Image
  Downloading https://files.pythonhosted.org/packages/0c/ec/51969468a8b87f631cc0e60a6bf1e5f6eec8ef3fd2ee45dc760d5a93b82a/image-1.5.27-py2.py3-none-any.whl
Collecting django (from Image)
  Downloading https://files.pythonhosted.org/packages/eb/4b/743d5008fc7432c714d753e1fc7ee56c6a776dc566cc6cfb4136d46cdcbb/Django-2.2.2-py3-none-any.whl (7.4MB)
     |████████████████████████████████| 7.5MB 1.1MB/s
Requirement already satisfied: pillow in c:\users\guillaume.dramais\appdata\local\programs\python\python37\lib\site-packages (from Image) (6.0.0)
Collecting sqlparse (from django->Image)
  Downloading https://files.pythonhosted.org/packages/ef/53/900f7d2a54557c6a37886585a91336520e5539e3ae2423ff1102daf4f3a7/sqlparse-0.3.0-py2.py3-none-any.whl
Requirement already satisfied: pytz in c:\users\guillaume.dramais\appdata\roaming\python\python37\site-packages (from django->Image) (2019.1)
Installing collected packages: sqlparse, django, Image
Successfully installed Image-1.5.27 django-2.2.2 sqlparse-0.3.0

C:\Users\guillaume.dramais>python -c "import DGS; DGS.test.dotest()"
Traceback (most recent call last):
  File "C:\Users\guillaume.dramais\AppData\Local\Programs\Python\Python37\lib\site-packages\DGS\_dgs_class_web.py", line 101, in <module>
    from imread import imread
ModuleNotFoundError: No module named 'imread'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\guillaume.dramais\AppData\Local\Programs\Python\Python37\lib\site-packages\DGS\__init__.py", line 47, in <module>
    from DGS._dgs_class_web import dgs
  File "C:\Users\guillaume.dramais\AppData\Local\Programs\Python\Python37\lib\site-packages\DGS\_dgs_class_web.py", line 103, in <module>
    from scipy.misc import imread
ImportError: cannot import name 'imread' from 'scipy.misc' (C:\Users\guillaume.dramais\AppData\Roaming\Python\Python37\site-packages\scipy\misc\__init__.py)

C:\Users\guillaume.dramais>pip install PIL
Collecting PIL
  ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL

**Comment by ddbuscombe** [comment]
```pip install imread```? (sorry, not near a computer to test)

**Comment by Dramais** [comment]
C:\Users\guillaume.dramais>pip install imread?
ERROR: Invalid requirement: 'imread?'

**Comment by ddbuscombe** [comment]
I can't recreate the issue. Scipy + Image is all you need, so if you have both of those installed, then

```from scipy.misc import imread```

should work

You could install ```imageio``` and change the code to read ```from imageio import imread```, but I'm not doing that because it would affect other users. Welcome to Python!

**Comment by Dramais** [comment]
Hi Dan,
Thanks, It works with the imageio solution ! 
I will try to compute my images.

C:\Users\guillaume.dramais>python -c "import DGS; DGS.test.dotest()"
===========================================
======DIGITAL GRAIN SIZE: WAVELET==========
===========================================
=CALCULATE GRAIN SIZE-DISTRIBUTION FROM AN=
====IMAGE OF SEDIMENT/GRANULAR MATERIAL====
===========================================
======A PROGRAM BY DANIEL BUSCOMBE=========
=========NAU, FLAGSTAFF, ARIZONA===========
========REVISION 3.0.12, OCT 2018===========
===========================================
Input image is C:\Users\guillaume.dramais\AppData\Local\Programs\Python\Python37\lib\site-packages\DGS\IMG_0229.JPG
Every 10 rows will be processed
Resolution is 1.0
Image will be filtered
Max scale as inverse fraction of data length: 8
Analysis of %s sub-octaves per octave: 8
Area to volume conversion constant = -0.5
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Processing image C:\Users\guillaume.dramais\AppData\Local\Programs\Python\Python37\lib\site-packages\DGS\IMG_0229.JPG
mean size = 41.30757768074605
stdev = 31.815703447602733
skewness = 0.023018686593425184
kurtosis = 0.1216758215481211
