### ISSUE TITLE
running the pyGDS

### ISSUE THREAD

**Issue by Dramais** [dbuscombe-usgs/pyDGS#8]
Hi Dan,
I tried to follow the procedure : 
I prepared an image and calculated the mm/pixel
I put the image in a folder

In the Python terminal 
I import DGS
I declare the image_file='/Users/guillaume.dramais/Desktop/Bureau/softs/DGS_data/image/test_img.jpg'
then the different values
density=10
...
But I guess there is something else to do, to run the processing?
I'm sorry, it's my first time with python.
Thanks
Guillaume

**Comment by ddbuscombe** [comment]
That's right. Then a few more variables to declare, and pass those to the ```DGS.dgs()``` program, like this:

```
import DGS
image_file = '/home/sed_images/my_image.png'
density = 10 # process every 10 lines
resolution = 0.01 # mm/pixel
dofilter =1 # filter the image
notes = 8 # notes per octave
maxscale = 8 #Max scale as inverse fraction of data length
verbose = 1 # print stuff to screen
x = -0.5
dgs_stats = DGS.dgs(image_file, density, resolution, dofilter, maxscale, notes, verbose, x)
```

**Comment by Dramais** [comment]
Hi Dan,
It's working, thanks.

Processing image C:/Users/guillaume.dramais/Desktop/Bureau/softs/DGS_data/image/test_img.tif
mean size = 1.6248879086027261
stdev = 1.2522247952073495
skewness = 0.030528397474942764
kurtosis = 0.2042430057068404
