### ISSUE TITLE
Issue Running the program

### ISSUE THREAD

**Issue by mmacfarland** [dbuscombe-usgs/pyDGS#9]
Afternoon,

I have run into some issues running pyDGS from my computer. Disclaimer: I'm not a programmer. That said, I've managed to work through a bunch of issues to get the Jupyter examples to load. I don't fully understand from the readme how to actually run the pyDGS program though, so I attempted to replace the 3 test images in the DGS folder (IMG_0202, _0229, and _0249) with the 3 images I would like the analyze (renamed to match) and then just run the Jupyter example again. When I run the program I get error messages and nothing seems to work. Pretty stuck on this one. Any help would be greatly appreciated before my head explodes.

Thanks in advance,
Matt

[Basic usage.docx](https://github.com/dbuscombe-usgs/pyDGS/files/3881274/Basic.usage.docx)

**Comment by ddbuscombe** [comment]
Apologies for the delay. I finally got around to updating this badly neglected repo! Please try again - hopefully it now works as expected. Also see https://github.com/dbuscombe-usgs/pyDGS/issues/11#issuecomment-656829703
